"""Assigning one paper to a class, and reading back what came in.

See models/classroom.py::ClassroomAssignment for why the whole class sits a
single pinned paper and why there is no submissions table.

Two things here are load-bearing and neither is obvious from the endpoint
names:

* ``create_assignment`` extends the generated paper's TTL past the due date.
  Without it the assignment quietly points at a purged cache row.
* ``exam_id_for_student`` is the only way a student reaches an assigned
  paper, and it deliberately does *not* go through generation — so sitting
  homework never spends the student's one free exam a day. The teacher's
  generation already paid for it.
"""
from __future__ import annotations

from datetime import datetime, timedelta
from typing import Any

from fastapi import HTTPException
from sqlalchemy import case, func
from sqlalchemy.orm import Session

from app.models.classroom import Classroom, ClassroomAssignment, ClassroomMember
from app.models.nvo_exam import NvoAttempt, NvoAttemptItem
from app.models.user import User
from app.services import nvo_exam_store
from app.services.classroom_service import _owned_classroom, list_members

#: How long an assigned paper outlives its due date. A week covers the
#: student who sits it late, the teacher who reopens it, and the parents'
#: evening afterwards.
PIN_GRACE = timedelta(days=7)

#: Used when an assignment has no due date at all. Still far past the 24h
#: default, because "no deadline" means "whenever", not "today".
PIN_NO_DUE_DATE = timedelta(days=30)


def _pin_until(due_at: datetime | None) -> datetime:
    if due_at is None:
        return datetime.utcnow() + PIN_NO_DUE_DATE
    return due_at + PIN_GRACE


def create_assignment(
    db: Session,
    *,
    classroom_id: int,
    teacher_id: int,
    title: str,
    exam_id: str,
    due_at: datetime | None = None,
    difficulty: str | None = None,
    format_: str | None = None,
    blueprint: str | None = None,
) -> ClassroomAssignment:
    """Pin a generated paper to a class.

    The paper is generated by the caller (the route) rather than here, so
    that this stays a pure database operation and the generation's cost and
    failure modes live in one place.
    """
    _owned_classroom(db, classroom_id, teacher_id)

    if not nvo_exam_store.extend_exam_expiry(exam_id, _pin_until(due_at)):
        # Refusing here beats creating an assignment whose paper 404s for
        # every student who opens it.
        raise HTTPException(
            status_code=404, detail="Изпитният вариант вече не е наличен."
        )

    assignment = ClassroomAssignment(
        classroom_id=classroom_id,
        teacher_id=teacher_id,
        title=title.strip(),
        exam_id=exam_id,
        due_at=due_at,
        difficulty=difficulty,
        format=format_,
        blueprint=blueprint,
    )
    db.add(assignment)
    db.commit()
    db.refresh(assignment)
    return assignment


def _owned_assignment(db: Session, assignment_id: int, teacher_id: int) -> ClassroomAssignment:
    """404 rather than 403, matching classroom_service: whether an assignment
    id exists is not something a stranger should be able to probe."""
    assignment = (
        db.query(ClassroomAssignment)
        .filter(
            ClassroomAssignment.id == assignment_id,
            ClassroomAssignment.teacher_id == teacher_id,
        )
        .one_or_none()
    )
    if assignment is None:
        raise HTTPException(status_code=404, detail="Заданието не е намерено.")
    return assignment


def _submitted_user_ids(db: Session, exam_id: str, student_ids: list[int]) -> set[int]:
    if not student_ids:
        return set()
    rows = (
        db.query(NvoAttempt.user_id)
        .filter(NvoAttempt.exam_id == exam_id, NvoAttempt.user_id.in_(student_ids))
        .all()
    )
    return {row.user_id for row in rows}


def _assignment_payload(db: Session, assignment: ClassroomAssignment) -> dict[str, Any]:
    student_ids = [m.student_id for m in list_members(db, assignment.classroom_id)]
    submitted = _submitted_user_ids(db, assignment.exam_id, student_ids)
    return {
        "id": assignment.id,
        "classroom_id": assignment.classroom_id,
        "title": assignment.title,
        "exam_id": assignment.exam_id,
        "difficulty": assignment.difficulty,
        "format": assignment.format,
        "blueprint": assignment.blueprint,
        "due_at": assignment.due_at.isoformat() if assignment.due_at else None,
        "is_open": assignment.is_open,
        "created_at": assignment.created_at.isoformat(),
        "student_count": len(student_ids),
        "submitted_count": len(submitted),
    }


def list_assignments_for_class(
    db: Session, *, classroom_id: int, teacher_id: int
) -> list[dict[str, Any]]:
    _owned_classroom(db, classroom_id, teacher_id)
    assignments = (
        db.query(ClassroomAssignment)
        .filter(ClassroomAssignment.classroom_id == classroom_id)
        .order_by(ClassroomAssignment.created_at.desc())
        .all()
    )
    return [_assignment_payload(db, a) for a in assignments]


def list_assignments_for_student(db: Session, *, student_id: int) -> list[dict[str, Any]]:
    """Homework, as the student sees it: only classes they actually joined."""
    rows = (
        db.query(ClassroomAssignment, Classroom)
        .join(Classroom, Classroom.id == ClassroomAssignment.classroom_id)
        .join(ClassroomMember, ClassroomMember.classroom_id == Classroom.id)
        .filter(ClassroomMember.student_id == student_id)
        .order_by(ClassroomAssignment.created_at.desc())
        .all()
    )

    exam_ids = [assignment.exam_id for assignment, _ in rows]
    submitted: set[str] = set()
    if exam_ids:
        submitted = {
            row.exam_id
            for row in db.query(NvoAttempt.exam_id)
            .filter(
                NvoAttempt.user_id == student_id,
                NvoAttempt.exam_id.in_(exam_ids),
            )
            .all()
        }

    return [
        {
            "id": assignment.id,
            "title": assignment.title,
            "class_name": classroom.name,
            "classroom_id": classroom.id,
            "due_at": assignment.due_at.isoformat() if assignment.due_at else None,
            "is_open": assignment.is_open,
            "submitted": assignment.exam_id in submitted,
            "created_at": assignment.created_at.isoformat(),
        }
        for assignment, classroom in rows
    ]


def exam_id_for_student(db: Session, *, assignment_id: int, student_id: int) -> str:
    """The pinned paper, for a student who belongs to the class.

    This is the credit-free path to an exam: no generation runs, so the free
    tier's one-exam-a-day quota is untouched. The teacher's generation is
    what was paid for, and a student locked out of their own homework by a
    quota would be indefensible.
    """
    assignment = (
        db.query(ClassroomAssignment)
        .filter(ClassroomAssignment.id == assignment_id)
        .one_or_none()
    )
    if assignment is None:
        raise HTTPException(status_code=404, detail="Заданието не е намерено.")

    member = (
        db.query(ClassroomMember)
        .filter(
            ClassroomMember.classroom_id == assignment.classroom_id,
            ClassroomMember.student_id == student_id,
        )
        .one_or_none()
    )
    if member is None:
        # Same 404 as an unknown id: membership of a class is not something
        # an outsider should be able to test for.
        raise HTTPException(status_code=404, detail="Заданието не е намерено.")

    if not assignment.is_open:
        raise HTTPException(status_code=410, detail="Заданието е приключено.")

    return assignment.exam_id


def close_assignment(
    db: Session, *, assignment_id: int, teacher_id: int
) -> ClassroomAssignment:
    assignment = _owned_assignment(db, assignment_id, teacher_id)
    assignment.is_open = False
    db.commit()
    db.refresh(assignment)
    return assignment


def reopen_assignment(
    db: Session, *, assignment_id: int, teacher_id: int
) -> ClassroomAssignment:
    assignment = _owned_assignment(db, assignment_id, teacher_id)
    assignment.is_open = True
    db.commit()
    db.refresh(assignment)
    return assignment


def build_assignment_report(
    db: Session, *, assignment_id: int, teacher_id: int
) -> dict[str, Any]:
    """Who sat it, how they did, and which questions the class fell over on.

    The per-question part is the reason assignments pin one paper: without
    that, "question 7" means a different question for every student.
    """
    assignment = _owned_assignment(db, assignment_id, teacher_id)

    members = list_members(db, assignment.classroom_id)
    student_ids = [m.student_id for m in members]
    users = (
        {u.id: u for u in db.query(User).filter(User.id.in_(student_ids)).all()}
        if student_ids
        else {}
    )

    attempts = (
        {
            a.user_id: a
            for a in db.query(NvoAttempt)
            .filter(
                NvoAttempt.exam_id == assignment.exam_id,
                NvoAttempt.user_id.in_(student_ids),
            )
            .all()
        }
        if student_ids
        else {}
    )

    rows: list[dict[str, Any]] = []
    for member in members:
        attempt = attempts.get(member.student_id)
        user = users.get(member.student_id)
        rows.append(
            {
                "student_id": member.student_id,
                "name": getattr(user, "name", None) or "Ученик",
                "submitted": attempt is not None,
                "percentage_correct": attempt.percentage_correct if attempt else None,
                "submitted_at": attempt.created_at.isoformat() if attempt else None,
            }
        )
    # Those who have not handed in float to the top: that is the list a
    # teacher acts on before the deadline.
    rows.sort(key=lambda r: (r["submitted"], r["percentage_correct"] or 0))

    questions: list[dict[str, Any]] = []
    attempt_ids = [a.id for a in attempts.values()]
    if attempt_ids:
        breakdown = (
            db.query(
                NvoAttemptItem.question_number.label("question_number"),
                NvoAttemptItem.topic_key.label("topic_key"),
                func.count(NvoAttemptItem.id).label("answered"),
                func.sum(
                    case((NvoAttemptItem.is_correct.is_(True), 0), else_=1)
                ).label("wrong"),
            )
            .filter(NvoAttemptItem.attempt_id.in_(attempt_ids))
            .group_by(NvoAttemptItem.question_number, NvoAttemptItem.topic_key)
            .order_by(NvoAttemptItem.question_number)
            .all()
        )
        from app.services import nvo_topics

        questions = [
            {
                "question_number": int(row.question_number),
                "topic_key": row.topic_key,
                "topic_label": nvo_topics.label(row.topic_key),
                "answered": int(row.answered or 0),
                "wrong": int(row.wrong or 0),
                "percent_correct": (
                    round(100 * (int(row.answered) - int(row.wrong)) / int(row.answered))
                    if row.answered
                    else 0
                ),
            }
            for row in breakdown
        ]

    return {
        **_assignment_payload(db, assignment),
        "student_count": len(student_ids),
        "submitted_count": len(attempts),
        "rows": rows,
        "questions": questions,
    }
