"""baseline schema

Snapshot of every table the app creates today, so that schema drift is tracked
from here on instead of being invented at runtime by `Base.metadata.create_all`.

IMPORTANT for existing deployments: their tables already exist, so running
`alembic upgrade head` against them would fail on the first CREATE TABLE. Adopt
the baseline with

    alembic stamp 754e61405945

which records the revision without re-running it. Only genuinely empty
databases should be brought up with `alembic upgrade head`.

Revision ID: 754e61405945
Revises:
Create Date: 2026-08-19 23:33:04.581695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '754e61405945'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companion_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('pairing_code', sa.String(length=6), nullable=False),
    sa.Column('exam_id', sa.String(length=64), nullable=True),
    sa.Column('question_ids', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('pairing_expires_at', sa.DateTime(), nullable=False),
    sa.Column('session_expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companion_sessions_id'), 'companion_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_companion_sessions_pairing_code'), 'companion_sessions', ['pairing_code'], unique=False)
    op.create_index(op.f('ix_companion_sessions_session_id'), 'companion_sessions', ['session_id'], unique=True)
    op.create_table('generated_exams',
    sa.Column('exam_id', sa.String(length=64), nullable=False),
    sa.Column('questions_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('exam_id')
    )
    op.create_index(op.f('ix_generated_exams_exam_id'), 'generated_exams', ['exam_id'], unique=False)
    op.create_index(op.f('ix_generated_exams_expires_at'), 'generated_exams', ['expires_at'], unique=False)
    op.create_table('grades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade_number')
    )
    op.create_index(op.f('ix_grades_id'), 'grades', ['id'], unique=False)
    op.create_table('nvo_generation_jobs',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('exam_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_nvo_generation_jobs_expires_at'), 'nvo_generation_jobs', ['expires_at'], unique=False)
    op.create_index(op.f('ix_nvo_generation_jobs_job_id'), 'nvo_generation_jobs', ['job_id'], unique=False)
    op.create_table('user_badges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('badge_key', sa.String(length=64), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_badges_id'), 'user_badges', ['id'], unique=False)
    op.create_index(op.f('ix_user_badges_user_id'), 'user_badges', ['user_id'], unique=False)
    op.create_table('user_xp_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('streak_multiplier', sa.Float(), nullable=False),
    sa.Column('today_xp', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_xp_profiles_id'), 'user_xp_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_xp_profiles_user_id'), 'user_xp_profiles', ['user_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('google_sub', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('picture', sa.String(length=500), nullable=True),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('is_admin', sa.Integer(), nullable=False),
    sa.Column('ai_exercises_today', sa.Integer(), nullable=False),
    sa.Column('ai_chat_today', sa.Integer(), nullable=False),
    sa.Column('ai_theory_today', sa.Integer(), nullable=False),
    sa.Column('nvo_exams_today', sa.Integer(), nullable=False),
    sa.Column('image_scans_today', sa.Integer(), nullable=False),
    sa.Column('usage_reset_date', sa.Date(), nullable=True),
    sa.Column('last_ai_chat_at', sa.DateTime(), nullable=True),
    sa.Column('last_ai_theory_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_sub'), 'users', ['google_sub'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('xp_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('xp_amount', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_xp_events_id'), 'xp_events', ['id'], unique=False)
    op.create_index(op.f('ix_xp_events_user_id'), 'xp_events', ['user_id'], unique=False)
    op.create_table('companion_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('session_fk', sa.Integer(), nullable=False),
    sa.Column('device_label', sa.String(length=64), nullable=True),
    sa.Column('paired_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_fk'], ['companion_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companion_devices_device_id'), 'companion_devices', ['device_id'], unique=True)
    op.create_index(op.f('ix_companion_devices_id'), 'companion_devices', ['id'], unique=False)
    op.create_index(op.f('ix_companion_devices_session_fk'), 'companion_devices', ['session_fk'], unique=False)
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_id'), 'topics', ['id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lessons_id'), 'lessons', ['id'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('completed_exercises', sa.Integer(), nullable=True),
    sa.Column('total_exercises', sa.Integer(), nullable=True),
    sa.Column('accuracy_percentage', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_progress_id'), 'user_progress', ['id'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.String(length=255), nullable=False),
    sa.Column('solution', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficultylevel'), nullable=True),
    sa.Column('exercise_type', sa.Enum('multiple_choice', 'numeric', 'algebra', name='exercisetype'), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    op.create_table('generated_lesson_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('detail_level', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lesson_id', 'detail_level', name='uq_generated_lesson_content_lesson_level')
    )
    op.create_index(op.f('ix_generated_lesson_content_id'), 'generated_lesson_content', ['id'], unique=False)
    op.create_index(op.f('ix_generated_lesson_content_lesson_id'), 'generated_lesson_content', ['lesson_id'], unique=False)
    op.create_table('lesson_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('completed_exercises', sa.Integer(), nullable=True),
    sa.Column('total_exercises', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_progress_id'), 'lesson_progress', ['id'], unique=False)
    op.create_table('user_daily_missions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mission_date', sa.Date(), nullable=False),
    sa.Column('mission_key', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('required_difficulty', sa.String(length=16), nullable=False),
    sa.Column('target_count', sa.Integer(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('xp_base', sa.Integer(), nullable=False),
    sa.Column('xp_bonus', sa.Integer(), nullable=False),
    sa.Column('route', sa.String(length=255), nullable=False),
    sa.Column('mission_order', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('xp_awarded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mission_date', 'mission_key', name='uq_user_daily_mission')
    )
    op.create_index(op.f('ix_user_daily_missions_id'), 'user_daily_missions', ['id'], unique=False)
    op.create_index(op.f('ix_user_daily_missions_mission_date'), 'user_daily_missions', ['mission_date'], unique=False)
    op.create_index(op.f('ix_user_daily_missions_user_id'), 'user_daily_missions', ['user_id'], unique=False)
    op.create_table('exercise_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('submitted_answer', sa.String(length=255), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_attempts_id'), 'exercise_attempts', ['id'], unique=False)
    op.create_table('user_mission_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mission_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['user_daily_missions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'exercise_id', name='uq_mission_exercise')
    )
    op.create_index(op.f('ix_user_mission_exercises_exercise_id'), 'user_mission_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_user_mission_exercises_id'), 'user_mission_exercises', ['id'], unique=False)
    op.create_index(op.f('ix_user_mission_exercises_mission_id'), 'user_mission_exercises', ['mission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_mission_exercises_mission_id'), table_name='user_mission_exercises')
    op.drop_index(op.f('ix_user_mission_exercises_id'), table_name='user_mission_exercises')
    op.drop_index(op.f('ix_user_mission_exercises_exercise_id'), table_name='user_mission_exercises')
    op.drop_table('user_mission_exercises')
    op.drop_index(op.f('ix_exercise_attempts_id'), table_name='exercise_attempts')
    op.drop_table('exercise_attempts')
    op.drop_index(op.f('ix_user_daily_missions_user_id'), table_name='user_daily_missions')
    op.drop_index(op.f('ix_user_daily_missions_mission_date'), table_name='user_daily_missions')
    op.drop_index(op.f('ix_user_daily_missions_id'), table_name='user_daily_missions')
    op.drop_table('user_daily_missions')
    op.drop_index(op.f('ix_lesson_progress_id'), table_name='lesson_progress')
    op.drop_table('lesson_progress')
    op.drop_index(op.f('ix_generated_lesson_content_lesson_id'), table_name='generated_lesson_content')
    op.drop_index(op.f('ix_generated_lesson_content_id'), table_name='generated_lesson_content')
    op.drop_table('generated_lesson_content')
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_user_progress_id'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_lessons_id'), table_name='lessons')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_topics_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_companion_devices_session_fk'), table_name='companion_devices')
    op.drop_index(op.f('ix_companion_devices_id'), table_name='companion_devices')
    op.drop_index(op.f('ix_companion_devices_device_id'), table_name='companion_devices')
    op.drop_table('companion_devices')
    op.drop_index(op.f('ix_xp_events_user_id'), table_name='xp_events')
    op.drop_index(op.f('ix_xp_events_id'), table_name='xp_events')
    op.drop_table('xp_events')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_sub'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_xp_profiles_user_id'), table_name='user_xp_profiles')
    op.drop_index(op.f('ix_user_xp_profiles_id'), table_name='user_xp_profiles')
    op.drop_table('user_xp_profiles')
    op.drop_index(op.f('ix_user_badges_user_id'), table_name='user_badges')
    op.drop_index(op.f('ix_user_badges_id'), table_name='user_badges')
    op.drop_table('user_badges')
    op.drop_index(op.f('ix_nvo_generation_jobs_job_id'), table_name='nvo_generation_jobs')
    op.drop_index(op.f('ix_nvo_generation_jobs_expires_at'), table_name='nvo_generation_jobs')
    op.drop_table('nvo_generation_jobs')
    op.drop_index(op.f('ix_grades_id'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_generated_exams_expires_at'), table_name='generated_exams')
    op.drop_index(op.f('ix_generated_exams_exam_id'), table_name='generated_exams')
    op.drop_table('generated_exams')
    op.drop_index(op.f('ix_companion_sessions_session_id'), table_name='companion_sessions')
    op.drop_index(op.f('ix_companion_sessions_pairing_code'), table_name='companion_sessions')
    op.drop_index(op.f('ix_companion_sessions_id'), table_name='companion_sessions')
    op.drop_table('companion_sessions')
    # ### end Alembic commands ###
